# Generated by Django 4.1.7 on 2023-03-14 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=30, null=True)),
                ('source_expence', models.CharField(blank=True, choices=[('Soft_Amount', 'Soft_Amount'), ('Fund', 'Fund')], max_length=20, null=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('fund_percent', models.IntegerField(default=0)),
                ('fund', models.BigIntegerField(default=0)),
                ('clean_amount', models.BigIntegerField(default=0)),
                ('gift', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.source')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
            managers=[
                ('filters', django.db.models.manager.Manager()),
            ],
        ),
    ]
