# Generated by Django 4.1.7 on 2023-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_report_source_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='clean_amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='fund',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='fund_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
